### ISSUE TITLE
[Android] BatchUpdateException constructor is not available

### ISSUE THREAD

**Issue by pavel-yazev-km** [xerial/sqlite-jdbc#1378]
**Describe the bug**
A non-existent  (in Android JDK) `BatchUpdateException` constructor is called by `JDBC3Statement.executeLargeBatch()`.

The exception in question:
```
java.lang.NoSuchMethodError: No direct method <init>(Ljava/lang/String;Ljava/lang/String;I[JLjava/lang/Throwable;)V in class Ljava/sql/BatchUpdateException; or its super classes (declaration of 'java.sql.BatchUpdateException' appears in /system/framework/core-oj.jar)
```

The incompatibility is caused by 4102c1d that replaced `int[]` argument with `long[]` that is [not supported](https://developer.android.com/reference/java/sql/BatchUpdateException) by Android JDK (any version).

**To Reproduce**
1. Create an empty Android App/Service project (any SDK level, confirmed with SDK 25) with Xerial SQLite.
2. Run this sample code on a real Android JDK (as an **instrumented** unit test, or as a part of a production APK)
```kotlin
import org.junit.Test
import java.sql.DriverManager

class BatchInsertTest {
    @Test
    fun reproduceBatchInsertException() {
        // Using in-memory db not to bother with files and paths.
        // The problem reproduces in file-based db as well.
        val connection = DriverManager.getConnection("jdbc:sqlite::memory:")

        val statement = connection.createStatement()
        statement.addBatch("AN INVALID SQL STATEMENT;")

        // This call throws the aforementioned exception. See full stacktrace below.
        statement.executeBatch()
    }
}
```

**Expected behavior**

The actual error should be correctly wrapped and passed up the stack trace:
```
org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (near "AN": syntax error)
```

**Logs**
The error with stacktrace:
```
java.lang.NoSuchMethodError: No direct method <init>(Ljava/lang/String;Ljava/lang/String;I[JLjava/lang/Throwable;)V in class Ljava/sql/BatchUpdateException; or its super classes (declaration of 'java.sql.BatchUpdateException' appears in /system/framework/core-oj.jar)
at org.sqlite.jdbc3.JDBC3Statement.executeLargeBatch(JDBC3Statement.java:245)
at org.sqlite.jdbc3.JDBC3Statement.executeBatch(JDBC3Statement.java:225)
at BatchInsertTest.reproduceBatchInsertException(BatchInsertTest.kt:15)
<...>
```

**Environment (please complete the following information):**
 - OS: Android 7.1 & 12
 - CPU architecture: arm64
 - sqlite-jdbc version 3.46.1.0

**The big picture**

My intention is not to fix this particular problem, but to highlight a fundamental issue with compatibility between Xerial SQLite and Android JDK.

The only requirement for Android, stated by Xerial SQLite (in [Supported Operating Systems](https://github.com/xerial/sqlite-jdbc?tab=readme-ov-file#supported-operating-systems) section) is "API Level **24+**".

This bug proves this statement to be wrong.

Since there's no defined backward compatibility guarantees for Android JDK, an assumption that everything that's available in Java will be available in Android JDK can create unexpected issues.

The question of compatibility with Android JDK should be treated with care.
A possible solution would be to analyze the code for compatibility with different Android SDK/JDK versions for every release.

In case there's something unavailable in Android SDK 24+ found to be used, either
a) a (preferably) code fix 
or
b) a stipulation in documentation may be made.

It would be very handy to have a list of Xerial SQLite functionality that can be safely used in Android environments.

There's a plugin that can be considered for doing this automatically: https://github.com/xvik/gradle-animalsniffer-plugin.
If supplied with Android SDK 24 headers, it could search all the calls in Xerial project and highlight those that are not available.
The result may be:
a) Considered as a build failure -- to fix & provide full compatibility
b) Analyzed and published -- to provide clear picture

**Comment by gotson** [comment]
> The incompatibility is caused by [4102c1d](https://github.com/xerial/sqlite-jdbc/commit/4102c1d445c2de550a62a2281c44bd3c86cfc139) that replaced `int[]` argument with `long[]` that is [not supported](https://developer.android.com/reference/java/sql/BatchUpdateException) by Android JDK (any version).

Can you clarify what is not supported by Android ? It's not clear from the link provided.

**Comment by gotson** [comment]
> There's a plugin that can be considered for doing this automatically: https://github.com/xvik/gradle-animalsniffer-plugin.
> If supplied with Android SDK 24 headers, it could search all the calls in Xerial project and highlight those that are not available.
> The result may be:
> a) Considered as a build failure -- to fix & provide full compatibility
> b) Analyzed and published -- to provide clear picture

That's interesting, i found one for Maven, along with Android signatures: https://github.com/open-toast/gummy-bears?tab=readme-ov-file#maven

Adding it to the build was easy, however i am not entirely sure of the results produced.

For example, when using API 26 signature, i am still getting some issues for methods that should be available in API 26:

```
[ERROR] /Users/groebroeck/Dev/sqlite-jdbc/src/main/java/org/sqlite/jdbc3/JDBC3PreparedStatement.java:174: Undefined reference: java.sql.JDBCType
[ERROR] /Users/groebroeck/Dev/sqlite-jdbc/src/main/java/org/sqlite/jdbc3/JDBC3PreparedStatement.java:174: Undefined reference: java.sql.JDBCType java.sql.JDBCType.valueOf(int)
[ERROR] /Users/groebroeck/Dev/sqlite-jdbc/src/main/java/org/sqlite/jdbc3/JDBC3PreparedStatement.java:174: Undefined reference: String java.sql.JDBCType.getName()
[ERROR] /Users/groebroeck/Dev/sqlite-jdbc/src/main/java/org/sqlite/jdbc4/JDBC4ResultSet.java:328: Undefined reference: java.time.LocalDate java.sql.Date.toLocalDate()
[ERROR] /Users/groebroeck/Dev/sqlite-jdbc/src/main/java/org/sqlite/jdbc4/JDBC4ResultSet.java:339: Undefined reference: java.time.LocalTime java.sql.Time.toLocalTime()
[ERROR] /Users/groebroeck/Dev/sqlite-jdbc/src/main/java/org/sqlite/jdbc4/JDBC4ResultSet.java:350: Undefined reference: java.time.LocalDateTime java.sql.Timestamp.toLocalDateTime()
```

You are right that this project's support for Android has always been second citizen at best. I think using this plugin would definitely help, and we could at least document what cannot be used, and if somehow we can make code changes, we could do that too.

With API level 24 there's a lot of use of `java.nio.file.Path` that Android apparently only supports since API level 26, so maybe raising the requirements to API level 26 would make sense.

**Comment by pavel-yazev-km** [comment]
@gotson thanks for your attention to this problem

> Can you clarify what is not supported by Android ? It's not clear from the link provided.

That's the call (you may find it in the aforementioned revision [4102c1d](https://github.com/xerial/sqlite-jdbc/commit/4102c1d445c2de550a62a2281c44bd3c86cfc139)):

<img width="896" height="521" alt="Image" src="https://github.com/user-attachments/assets/169e3c58-b157-4fe7-b049-0034e39cf3f7" />

Apparently, this c-tor is called now:

<img width="1645" height="666" alt="Image" src="https://github.com/user-attachments/assets/780440cf-fc9b-4efb-9974-5bdd5f439e04" />

[Java Doc / BatchUpdateException](https://docs.oracle.com/javase/8/docs/api/java/sql/BatchUpdateException.html)

But there's not a single available `BatchUpdateException` c-tor with `long[]` args in [Android SDK](https://developer.android.com/reference/java/sql/BatchUpdateException) (any version). So even if the requirement is bumped to 26+, this wont solve this particular case (it can solve some others, of course).

**Comment by gotson** [comment]
@pavel-yazev-km please check https://github.com/xerial/sqlite-jdbc/pull/1395
